### ISSUE TITLE
mocha-parallel-tests cannot take error screenshot by suing mochawesome-screenshots

### ISSUE THREAD

**Issue by dylanzhang123456** [mocha-parallel/mocha-parallel-tests#185]
background:
my team is using mochawesome-screenshots to take screenshot after error happened,
this is very helpful when script is failed.

my command is:
mocha-parallel-tests ./test/spec/XXX.js --reporter mochawesome-screenshots --reporter-options jsonReport=true,clearOldScreenshots=false,shortScrFileNames=true --timeout=60000

can you help investigate how to make mocha-parallel-tests can support mochawesome-screenshots 
to take error screenshots?

Thank you very much!

**Comment by dylanzhang123456** [comment]
Hi,@1999

Just like I comment before,I used this command to run my project:

mocha-parallel-tests ./test/spec/XXX.js --reporter mochawesome-screenshots --reporter-options jsonReport=true,clearOldScreenshots=false,shortScrFileNames=true --timeout=60000

it can't set screenshots to mochawesome html report with no error message in system console,

clue: piece of html report:

```
<div class="test-error-scr collapse">
            <pre><code class="hljs small"><img src="./screenshots/1533276470440.png"></code></pre>
</div>
```

but I can'f find picture:./screenshots/1533276470440.png in my project.


Fortunately,I found another way to set screenshots:
mochawesome-screenshots module provide a backup way that users can set screenshots by using "logReport" in **every** afterEach hook.

It helps if mocha-parallel-tests support mochawesome-screenshots to grab pictures when test cases failed  rather than using "logReport" in **every** afterEach hook.

Thank you so much!

**Comment by 1999** [comment]
Gotcha. As far as I understand `mochawesome-screenshots` are using protractor tests which is using webdriver inside. I suspect that this can be the problem - too many steps here and each of them runs in a separate process.

mochawesome-screenshota docs say that it also supports some kind of parallel tests execution, maybe that's what you need?

> Use 'multiReport = true' for parallel test execution (adding timestamp in report file name), or change report name in tests or hooks for shardTestFiles option:

Anyway, it's very difficult for me to reproduce this issue because I'm not using Angular and it looks like I need to run my tests on an Angular app and I don't have any. So if you want me to fix this, please create some kind of reproducable case in a repo so I can run it on my machine and see the error.

**Comment by 1999** [comment]
Closing because of the inactivity for 2 weeks.
