### ISSUE TITLE
Support for --file option

### ISSUE THREAD

**Issue by sstarnaud** [mocha-parallel/mocha-parallel-tests#222]
Is it possible to add support for the mocha '--file' option that would help in executing root level hooks?

**Comment by 1999** [comment]
Sure, why not. I guess the only important thing to notice is that this `--file` thing will be executed for all suites, i.e. if you rely on some "state" from this `--file` in all your tests, this will not work with `mocha-parallel-tests`

**Comment by sstarnaud** [comment]
@1999 Maybe this won't work for what I'm trying to achieve.  I'm trying to have a 1 time 'before' that runs before all test executions and then a 1 time 'after' that runs after all test executions are complete.  This works with the '--file' option in mocha but when I try this with mocha-parallel-tests it throws this "error: unknown option `--test'".

**Comment by 1999** [comment]
Not really unfortunately

**Comment by nekiscz** [comment]
Do you have some guidelines or how to for contributors?

**Comment by 1999** [comment]
Probably not. The project right now is not that complicated. Linting is preconfigured and editorconfig should help you start writing the code. For all pull requests, it's great to add some test - they are in "test" directory. Other than that, feel free to reach me out and ask for help.

**Comment by alvaroemmanuel** [comment]
The --file option would be a nice adding, I have an issue to load global async hooks.
I know this would not be the perfect solution, since it will be called for each process, but will still be an improvement that would let setup and teardown things on a process/suite basis.

**Comment by misko-frame** [comment]
+1

**Comment by 1999** [comment]
@Favna that's the spirit :) The flow is pretty easy - you create a PR which contains a test, we review it together and merge. The tests are in "test" folder, see [delay option](https://github.com/mocha-parallel/mocha-parallel-tests/tree/master/test/delay) support test for example.

**Comment by Favna** [comment]
@1999 I gave it a shot but I can't quite figure out tests. Maybe you could have a look? Here is the compare of the changes I've made so far: https://github.com/mocha-parallel/mocha-parallel-tests/compare/master...Favna:feat/file_option, based on this branch: https://github.com/Favna/mocha-parallel-tests/tree/feat/file_option. 

For some reason adding this code also has many other tests fail, but some pre-existing tests are already failing on a clean version of master. Not sure if that's just because I'm on Windows? Do you guys use a Unix system to develop?

**Comment by 1999** [comment]
> Not sure if that's just because I'm on Windows
That's the reason: mocha-parallel-tests doesn't work well on Windows: https://github.com/mocha-parallel/mocha-parallel-tests/pull/254. If you can use Linux/Mac to run your tests that would be easier for now. Also, could you please raise a PR so we can continue the convo there?

**Comment by Favna** [comment]
Took quite my time but I've been busy. Just fixed the tests using my Macbook and created PR #267

**Comment by DanMossa** [comment]
Any progress on this? ;D

**Comment by Favna** [comment]
Pretty much only my PR #267 @DanMossa. I haven't really made time to look into why tests are flaky and I haven't been much motivated either since I have a strong preference for the Jest framework myself these days. My only interest in Mocha at the time lay in a single legacy app we still had at work but we've pretty much deprecated that app now as well.
